### ISSUE TITLE
values for the lines 

### ISSUE THREAD

**Issue by pagallego** [react-map/leaflet.migrationLayer#10]
Can you please make an example on how to use the values to define the thicknesses of each line ? I 

this is the data : 

data = [{"from":[-118.2705,33.9984],"to":[-122.789336,37.920458],"labels":["Los Angeles","San Francisco"],"color":"#ff3a31","value":50}];

do i need to add --> arcWidth: data.values ??

**Comment by jaks6** [comment]
Hello,

I was able to do this by using the [src.js ](https://github.com/lit-forest/leaflet.migrationLayer/blob/master/src/src.js) version of the library, (not the one in "dist" folder ).

It seems that the minified version in the "dist" folder of the library does not  [include the pull request for adjusting arc width based on the value](https://github.com/lit-forest/leaflet.migrationLayer/pull/8).

**Comment by Sylvenas** [comment]
Yes, thanks for finding the problem, but I haven't had time to update it recently, can you initiate  a pull request and I can merge it in?
