### ISSUE TITLE
Migration layer disappears after zooming

### ISSUE THREAD

**Issue by yalhassanpro** [react-map/leaflet.migrationLayer#22]
This is the first time I am using this plugin and I am facing a challenge. The map and migration layer load as expected, however, the migration layer disappears when I zoom in or out and does not reappear until I reload the page. 

There are no errors in the console, I have changed browsers, and tried it on different computers but the problem still persists. I even recreated the demo on this page but the migration layer still disappears. If anybody encountered this same challenge in the past, please help me with the solution.

All ideas are welcomed. Thank you.

**Comment by yalhassanpro** [comment]
In case someone encounters a similar problem, this is how I solved it.

- Visit the official demo page of this library. https://lycheelin.github.io/leaflet.migrationLayer/
- Right-click on the page and select "inspect". Choose the "Sources" tab (I use Chrome).
- Click on "src.js" under the "src" folder. Copy the entire code in the src.js file.
- Go to your working directory and replace the "src.js" code with the one you just copied.

I don't know why but it worked for me.

**Comment by Sylvenas** [comment]
Maybe it's because I didn't update in time, the source code, if you have time, can you help initiate a pr, I will merge it in.

**Comment by yalhassanpro** [comment]
Okay, sounds great.
