### ISSUE TITLE
Broken link to demo

### ISSUE THREAD

**Issue by hansenmc** [react-map/leaflet.migrationLayer#6]
The link to check out a demo is broken. https://react-map.github.io/leaflet.migrationLayer/ does not exist.

> A demo is available on the Github Pages webpage for leaflet.migrationLayer [Check out demo!](https://react-map.github.io/leaflet.migrationLayer/).

**Comment by hansenmc** [comment]
Looks like it should point to: https://lit-forest.github.io/react-map.github.io/leaflet.migrationLayer/

**Comment by Sylvenas** [comment]
It's fixed now, thanks.
